### ISSUE TITLE
Trouble when updating from 1.4 to 1.5

### ISSUE THREAD

**Issue by spoldman** [babel/babel-preset-env#334] opened 2017-05-22 16:16 UTC
I'm getting an error after update of this package. I did a bit of digging and it looks like _targetsParser2 i undefined in the built source. 

Here is the stack trace 

TypeError: Cannot read property 'default' of undefined (While processing preset: "C:\\Code\\Frontend\\Cosmic\\packages\\mono-cli\\node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "C:\\Code\\Frontend\\Cosmic\\packages\\mono-cli\\node_modules\\babel-preset-env\\lib\\index.js")
    at buildPreset (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-preset-env\lib\index.js:148:36)
    at C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:317:46
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Code\Frontend\Cosmic\packages\mono-cli\node_modules\babel-register\lib\node.js:154:7)

**Comment by hzoo** [comment] 2017-05-22 16:17
Are you using 1.5 or 1.5.1?

**Comment by spoldman** [comment] 2017-05-22 16:22
Both 1.5 and 1.5.1 give me this error

**Comment by hzoo** [comment] 2017-05-22 16:23
Can you provide more information? Config etc

**Comment by spoldman** [comment] 2017-05-22 16:32
Sure, I'm using it like this in my code. 

require('babel-register')({ // eslint-disable-line
	babelrc: false,
	ignore: false,
	only: /src/,
	presets: [
		['env', { node: 'current' }]
	],
	plugins: [
		'transform-export-extensions',
		'add-module-exports',
		'transform-runtime',
		'syntax-object-rest-spread',
		'transform-object-rest-spread'
	]
})

**Comment by spoldman** [comment] 2017-05-22 16:40
Using node 7.1

**Comment by spoldman** [comment] 2017-05-22 16:59
Updated to node 7.10 and the error still occurs.

**Comment by loganfsmyth** [comment] 2017-05-22 18:46
Your usage of `ignore: false` is causing your issue. If you want to compile things in `node_modules` you should have a whitelist of the modules you actually want to compile, otherwise you're doing tons of extra work. e.g.

    ignore: /node_modules\/(?:!some-module|another_module|third_module)/

to compile just those modules.

This issue was caused because of the changes in https://github.com/babel/babel-preset-env/pull/324 because that `babel` key in the `package.json` is published to npm, so anyone using `ignore: false` will be telling `babel-preset-env` to compile _itself_, hence the circular dependency failure in your error.

I'll leave it up to others as to whether this is worth changing. `ignore: false` is never a good idea in the current architecture. We've talked about changing the behavior of file-based configs in 7.x which would fix this, but we haven't settled on anything yet.

**Comment by spoldman** [comment] 2017-05-23 10:56
I removed the ignore options, reinstalled the package and I had no success. Still having the same error using v1.5

**Comment by existentialism** [comment] 2017-05-27 04:07
@spoldman any chance you could put up a small repo that reproduces the problem?

**Comment by tomatau** [comment] 2017-06-23 08:39
I have the same problem, I need to include some node_modules because of the infrastructure at work.

So our entry looks like this:

```
require('babel-polyfill')
require('babel-register')({
  only: [
    /src/,
    /nowtv-web-toolkit/,
    /nowtv-assurance-shared/,
  ],
})
require('./server-start')
```

This should be still using the default of `ignore: /node_modules/` though so I don't get why it would be attempting to compile the babel-preset-env lib...

.babelrc:
```
{
  "presets": [
    ["env", { "targets": { "node": true } }],
    "react"
  ],
```

We run similar options through webpack when bundling and it works fine, this just breaks on our server side render logic.

**Comment by spoldman** [comment] 2017-08-04 15:18
I'm still having this issue trying to update to version 1.6. I had some time to create a repository to replicate this issue hope that helps solving the issue.

It can be found here: https://github.com/spoldman/Update-issue-with-babel-preset-env

**Comment by existentialism** [comment] 2017-08-04 16:01
@spoldman thanks for creating the repo! Just to be clear, you said this worked with `babel-preset-env@1.4.0`? I'm getting the same error with that version.

**Comment by spoldman** [comment] 2017-08-08 13:14
I double checked and yes, it works using version 1.4. 

![image](https://user-images.githubusercontent.com/10643226/29073514-6a976106-7c3b-11e7-9bf1-ea3afb52de53.png)

**Comment by existentialism** [comment] 2017-08-08 15:08
@spoldman can you try changing your `only` to `only: /\.\/src/`?

@yavorsky and I were digging into this... and it looks like in browserslist 2.x (which we bumped in 1.4 -> 1.5), they switched to using `caniusedb-lite`, which contains a module named `iframe-srcdoc`... and due to some fun gotchas/bugs with only (which should be fixed in 7.0), it caused things to fail silently.

**Comment by spoldman** [comment] 2017-08-09 10:18
@existentialism Looks like this works. What changed to cause this?

**Comment by existentialism** [comment] 2017-08-09 12:51
Combination of us upgrading to browserslist 2.0 during 1.4 -> 1.5, which happened to expose one (of many) bugs with using "only" and babel-register, have you tried using Babel 7 at all? We hope many of the issues there have been resolved, and if not, we should definitely get it taken care of!

Thanks again for the cooperation and patience!

**Comment by spoldman** [comment] 2017-08-09 16:58
I will look into updating to babel 7. Thanks for the help.

**Closed** 2017-08-09 19:34 UTC
Labels: question
