### ISSUE TITLE
transform-class-properties together with babel env

### ISSUE THREAD

**Issue by marcoacierno** [babel/babel-preset-env#417] opened 2017-09-16 17:27 UTC
I'm having difficulties using the plugin transform-class-properties together with babel-preset-env, even if it's defined in the `.babelrc` the build still says 'Missing class properties transform.'. Searching online I found that you need to use transform-class-properties before the others (or after, can't recall now) but as far as I know I can't change the execution order in the babelrc.

How can I solve this problem?

The error

```
SyntaxError: /Users/marco/projects/TAOPP/Frontend/js/App.js: Missing class properties transform.
  32 |
  33 | class App extends React.Component {
> 34 |     static childContextTypes = {
     |     ^
```

My .babelrc

```
{
    'presets': [
        ['env', {
            'targets': {
                'browsers': ['last 2 versions'],
            },
            'modules': false,
            'debug': true,
        }],
        'react',
    ],
    'plugins': [
        'transform-class-properties',
        'transform-object-rest-spread',
    ],
    'env': {
        'server': {
            'presets': [
                ['env', {
                    'modules': 'commonjs',
                }],
            ]
        },
        'production': {
            'presets': ['minify'],
        },
    },
}
```

(p.s. the documentation is not really clear about how `.babelrc` handles the env merge, so I'm not sure that my babelrc is correct)

**Comment by WillBeebe** [comment] 2017-09-30 20:10
I'm having an issue using plugins listed in the `.babelrc` with `preset-env` as well 👍 . I had to go back to `preset-es2015`

**Comment by WillBeebe** [comment] 2017-09-30 20:14
Here's my `package.json` file that doesn't work.
```
{
  "name": "Api-graphql",
  "description": "Api-graphql for Firebase",
  "scripts": {
    "package-functions": "babel 'functionsES6' --out-dir 'functions' --copy-files --ignore 'node_modules'"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.1",
    "babel-plugin-add-module-exports": "0.2.1",
    "babel-plugin-transform-imports": "^1.4.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "latest",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-stage-2": "6.24.1",
    "eslint": "4.8.0",
    "eslint-config-airbnb": "15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0"
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "loose": true,
          "modules": false,
          "targets": {
            "node": "8"
          },
          "debug": true
        }
      ],
      "stage-2",
      "flow"
    ],
    "plugins": [
      "add-module-exports",
      "transform-flow-strip-types",
      "transform-runtime",
      "transform-imports"
    ]
  },
  "private": true
}
```

**Comment by yavorsky** [comment] 2017-10-01 13:54
@WillBeebe What kind of issue do you have? Some transformations missing?

**Comment by loganfsmyth** [comment] 2017-10-01 18:13
@marcoacierno There merge logic for `env` config blocks here is likely the culprit. I'd recommend if you're going to use `env` block, you duplicate the config into each `env`.

In Babel 7.x we'll be adding a `.babelrc.js` file to allow people to move away from the `env` block entirely in favor of just programmatically constructing the config you want.

**Comment by marcoacierno** [comment] 2017-10-01 18:23
@loganfsmyth Hmm I am not sure, I had this issue even with the full configuration in each env (in fact I encoured it with the full babel conf in each env). The only way to fix this is to not use babel preset env and manually add each plugin/transform. Doing it manually allows me to put transform-class-properties first, so this problem doesn't happen...

**Comment by loganfsmyth** [comment] 2017-10-01 18:46
I'd try it with a config like
```
{
  'env': {
    'development': {
      'presets': [
        ['env', {
          'targets': {
            'browsers': ['last 2 versions'],
          },
          'modules': false,
          'debug': true,
        }],
        'react',
      ],
      'plugins': [
        'transform-class-properties',
        'transform-object-rest-spread',
      ],
    },
    'server': {
      'presets': [
        ['env', {
          'targets': {
            'browsers': ['last 2 versions'],
          },
          'modules': 'commonjs',
        }],
        'react',
      ],
      'plugins': [
        'transform-class-properties',
        'transform-object-rest-spread',
      ],
    },
    'production': {
      'presets': [
        ['env', {
          'targets': {
            'browsers': ['last 2 versions'],
          },
          'modules': false,
          'debug': true,
        }],
        'react',
        'minify',
      ],
      'plugins': [
        'transform-class-properties',
        'transform-object-rest-spread',
      ],
    },
  },
}
```

**Comment by marcoacierno** [comment] 2017-10-01 19:11
I can try again, but as I said above, that was my initial configuration (not working) because I didn't knew if env correctly merge everything correctly...

**Comment by loganfsmyth** [comment] 2017-10-01 19:43
Using the `'env':` block in your config merges things with the top-level config, but it doesn't do anything to ensure that things are merged in the correct ordering. In this case, that merging is likely not doing what you want it to do, causing the issue you're describing. By moving everything out of the top level of the config, there's nothing specific to merge and therefore things should work. I don't it's not pretty though.

**Comment by mpelham** [comment] 2017-10-04 00:49
@WillBeebe 
I was running into the same issue, though our project uses Webpack. 

However, I created a really dumb example to repro:
*.babelrc*
```
{
  "presets": [["env", {"debug": true}], "react"],
  "plugins": ["transform-class-properties"]
}
```

*index.js*
```
import React, { Component } from 'react';

class TestClass extends Component {
    static foo = 'bar';
    render () {
        return <div>Hi</div>;
    }
}

console.log(TestClass);

export default TestClass;
```

*package.json*
```
{
    "name": "babel-preset-env-test",
    "version": "0.0.0",
    "private": true,
    "description": "",
    "main": "",
    "scripts": {},
    "dependencies": {
        "react": "15.5.4"
    },
    "devDependencies": {
        "babel-cli": "6.24.1",
        "babel-core": "6.24.1",
        "babel-eslint": "^7.2.3",
        "babel-loader": "7.1",
        "babel-plugin-syntax-decorators": "6.13.0",
        "babel-plugin-transform-class-properties": "6.11.5",
        "babel-plugin-transform-flow-strip-types": "^6.21.0",
        "babel-plugin-transform-object-rest-spread": "6.8.0",
        "babel-plugin-transform-react-jsx": "6.8.0",
        "babel-plugin-transform-runtime": "6.12",
        "babel-preset-env": "^1.6.0",
        "babel-preset-react": "^6.24.1",
        "babel-register": "^6.24.1",
        "babel-runtime": "6.9.2"
    }
}
```

And confirmed that running `babel-node index.js` did not break, here's the output:
```
babel-preset-env: `DEBUG` option

Using targets:
{}

Modules transform: commonjs

Using plugins:
  check-es2015-constants {}
  transform-es2015-arrow-functions {}
  transform-es2015-block-scoped-functions {}
  transform-es2015-block-scoping {}
  transform-es2015-classes {}
  transform-es2015-computed-properties {}
  transform-es2015-destructuring {}
  transform-es2015-duplicate-keys {}
  transform-es2015-for-of {}
  transform-es2015-function-name {}
  transform-es2015-literals {}
  transform-es2015-object-super {}
  transform-es2015-parameters {}
  transform-es2015-shorthand-properties {}
  transform-es2015-spread {}
  transform-es2015-sticky-regex {}
  transform-es2015-template-literals {}
  transform-es2015-typeof-symbol {}
  transform-es2015-unicode-regex {}
  transform-regenerator {}
  transform-exponentiation-operator {}
  transform-async-to-generator {}
  syntax-trailing-function-commas {}
{ [Function: TestClass] foo: 'bar' }
```

Thusly, I assumed it had likely something to do with our Webpack config and not with `babel-preset-env`.

I'm not sure if this is the "correct" fix, but I discovered that adding into our `babel-loader` module's plugins `transform-class-properties` resolved this issue and got me my sweet sweet statics. 

I hope this helps you out / provides some more information for the next person who runs into this issue.

**Comment by Always-Sunny** [comment] 2017-10-11 06:15
Having the same problem ^^

I thought it was the order of my presets/plugins, but I've tried every possible combination and nothing has worked. I've stuck with the ordering as determined by the docs: http://babeljs.io/docs/plugins#pluginpreset-ordering

"Plugins run before Presets.
Plugin ordering is first to last.
Preset ordering is reversed (last to first)."

According to the babel docs, this is the correct ordering (except I have 'env' instead of 'es2015'):
```
{
  "presets": [
    "es2015",
    "react",
    "stage-2"
  ]
}

```
and my plugins come before my presets:

```
"plugins": [
      "react-hot-loader/babel",
      "transform-es2015-arrow-functions"
    ],
    "presets": [
      "env",
      "react",
      "stage-2"
    ]
```

I have gone through multiple plugins and presets to get the arrow binding functions to work and nothing has worked. I tried switching out 'env' for 'es2015' and I tried using "transform-class-properties" in stead of "transform-es2015-arrow-functions". Stage-2 is supposed to take care of the transform-class-properties, but it's not. 

And when I tried to switch out 'env' for 'es2015', after yarn remove babel-preset-es2015, node would throw an error saying it couldn't find the preset env even after I removed it from my dependencies and swapped it for es2015 in my .babelrc

**Comment by milesj** [comment] 2017-10-11 17:24
FWIW, this currently works for me:

```
{
  babelrc: false,
  comments: false,
  plugins: [
    'transform-export-extensions',
    ['transform-dev', {
      evaluate: false,
    }],
    'transform-runtime',
  ],
  // Order is important!
  presets: [
    ['env', {
      targets: { ie: '10' },
      useBuiltIns: true,
    }],
    'stage-2',
    'react',
    'flow',
  ],
}
```

**Comment by Tokimon** [comment] 2017-10-27 15:53
It could be great if this worked out of the box with `babel-preset-env` as browsers should one day support this, thus automatically removing the transform plugins. It is the whole idea behind this module isn't it? Set it once and don't worry about future support? but when features like static class properties and object spread operator isn't supported it kinda defies the purpose doesn't it?

**Comment by existentialism** [comment] 2017-10-27 15:57
@Tokimon support for this has landed in 2.x via `shippedProposals` option.

For ref: https://github.com/babel/babel/tree/master/experimental/babel-preset-env#shippedproposals

**Comment by hzoo** [comment] 2017-10-27 16:00
It depends on if you mean Stage 4 or not, which is why we added the in-between option. It doesn't deify the purpose just the definition of what is supported or not (Stage 3 things can be removed or changed too)

**Closed** 2017-10-30 16:00 UTC
