### ISSUE TITLE
Bug in computed properties implementation in Chrome < 52

### ISSUE THREAD

**Issue by ahutchings** [babel/babel-preset-env#54] opened 2016-11-30 19:47 UTC
In our app, we were experiencing a crash in certain scenarios when using computed properties in Chrome < 52. This bug has been fixed in Chrome 52 and above.

https://bugs.chromium.org/p/v8/issues/detail?id=5033
https://bugs.chromium.org/p/chromium/issues/detail?id=625868

Given that, would you accept a pull request to bump the required Chrome version to 52 for transform-es2015-computed-properties? I suppose Opera would have been affected as well. Would this need to be authored as an override in the build-data.js script?

cc @jayfunk

**Comment by hzoo** [comment] 2016-11-30 20:09
II think we should figure out a way to override it since everytime we run the build script it would change it back to the old value?

I think it depends on the case that it happens as well?

**Comment by chicoxyzzy** [comment] 2016-11-30 22:20
Probably we can add a test to `compat-table`. But I'm afraid that there is no even test262 test for it.

**Comment by ljharb** [comment] 2016-12-02 03:25
We should add a test to both - test262 takes PRs as well :-)

**Comment by fhinkel** [comment] 2016-12-04 14:58
V8 has a regression test for this case (https://github.com/v8/v8/blob/master/test/mjsunit/regress/regress-5033.js). I'm not sure how much sense this makes to add a test to test262, since the issue only happened with the optimizing compiler.

**Comment by ljharb** [comment] 2017-06-13 02:02
Um, why are we using this bot? "Stale" issues should remain open indefinitely to ensure discoverability.

**Comment by ljharb** [comment] 2017-06-13 03:10
If there's no way to reliably check for this without `%OptimizeFunctionOnNextCall`, then definitely no test could be written for it.

That said, if something's crashing in Chrome < 52, it's a bug, and it needs fixing.

If bumping the required version for the transform to v52 is a simple fix for this problem - especially since few users will run into this anyways - then that seems like the right path.

**Closed** 2017-10-30 15:55 UTC
Labels: area: compat-table, area: test262, i: bug, i: question, Tag: Bug Fix
