### ISSUE TITLE
Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by adlk** [babel/babel-preset-env#186] opened 2017-03-03 14:49 UTC
I'm working with the [`electron-forge`](https://github.com/electron-userland/electron-forge) setup and I'm trying to dynamically require an external node_module that is located in `/Users/name/plugin` Unfortunately babel-preset-env is trying to resolve the preset relative to the required module instead of the local module. 

**Console output when trying to require the module**
```
Error: Couldn't find preset "env" relative to directory "/Users/name/plugin/7ada6103-7315-4c24-93f3-4a3a6a0fa7ee"
    at /Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/name/project/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/name/project/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/name/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at BabelCompiler.compileSync (/Users/name/project/node_modules/electron-compilers/lib/js/babel.js:76:26)
```

**contents of .compilerc**
```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          [
            "env",
            {
              "targets": {
                "electron": "1.4.15"
              }
            }
          ],
          "react"
        ],
        "plugins": [
          "transform-decorators-legacy",
          "transform-flow-strip-types",
          "transform-class-properties",
          "transform-async-to-generator"
        ],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          [
            "env",
            {
              "targets": {
                "electron": "1.4.15"
              }
            }
          ],
          "react"
        ],
        "plugins": [
          "transform-decorators-legacy",
          "transform-flow-strip-types",
          "transform-class-properties",
          "transform-async-to-generator"
        ],
        "sourceMaps": "none"
      }
    }
  }
}
```

**How to test this issue:**
Use a clean project (`electron-forge init`) and try to import any random module from a folder that is not within `module.paths`

**Comment by entozoon** [comment] 2017-03-06 11:33
+1

**Comment by JPeer264** [comment] 2017-03-07 20:30
@adlk which `babel-core` version do you use?

**Comment by loganfsmyth** [comment] 2017-03-07 20:33
It sounds like you have no installed `babel-preset-env`?

**Comment by JPeer264** [comment] 2017-03-07 20:41
@loganfsmyth I got this issue earlier today using `gulp-babel` which uses an older `babel-core` version. I installed a newer version with `npm i babel-core -D` and it was solved. Maybe @adlk got the same

**Comment by nashwaan** [comment] 2017-03-12 06:24
As suggested by @loganfsmyth installing `babel-preset-env` worked for me.

**Comment by existentialism** [comment] 2017-03-12 15:40
Closing for now as there doesn't look like there's anything actionable.

@JPeer264 and @nashwaan please let us know if you run into any more issues related to `babel-preset-env`!

**Comment by existentialism** [comment] 2017-03-12 15:42
Actually, will wait until OP responds.

**Comment by adlk** [comment] 2017-03-12 18:51
@JPeer264 tried it with the latest version of `babel-core`
@nashwaan was using `babel-preset-env`v1.1.8 and upgraded to 1.2.1 but this didn't do the trick either.

**Comment by JPeer264** [comment] 2017-03-12 19:25
@adlk hm strange - are you using babel as cli?

**Comment by adlk** [comment] 2017-03-13 09:14
@JPeer264 yup

**Comment by justechn** [comment] 2017-03-13 14:47
I seem to be having the same problem. I am also using electron-forge and I am trying to include a package that is not in node_modules. I have tried all the above suggestions and the only thing that works is what @adlk suggested. I looked in node_modules/babel-core/package.json and it says `"version": "6.24.0"`

**Comment by trusktr** [comment] 2017-03-19 21:45
I can confirm that I get this problem when using npm v2, but no problems when using v4.

duplicate: #219 

You can reproduce with this simple babelrc:

```sh
{
  "presets": [
      "env"
  ],
  "plugins": [
      "transform-es2015-modules-umd"
  ]
}
```

make a simple js file in `src/app.js` then run the following:

```sh
npm install -g "npm@^2"
npm install babel-cli babel-preset-env babel-plugin-transform-es2015-modules-umd
./node_modules/.bin/babel src -d dist
```

That will cause the error.

Then, if you update to npm v4, the error will go away.

**Comment by adlk** [comment] 2017-03-19 21:47
@trusktr hmm that's weird. I'm running `npm 4.1.2`

**Comment by trusktr** [comment] 2017-03-19 21:48
Same error for me, same line and column number, when using npm v2.

Here's a physical repro: https://github.com/trusktr/tween.js/tree/ddba437d51b8af9d4f1b84dec4ca4533e0a4d09e

You can clone that and checkout that commit, then just run `npm install` with npm v2 which eventually triggers the error.

**Comment by trusktr** [comment] 2017-03-19 21:48
@adlk I'm not getting the error with npm v4.4

**Comment by trusktr** [comment] 2017-03-19 21:50
@adlk Hmmm, something is fishy, I was on npm v4, and I was able to run babel just fine with no errors just a moment ago, but now I can not. Investigating...

**Comment by adlk** [comment] 2017-03-19 21:51
Yep, I've just updated to the latest npm version and I'm still getting the error :(

**Comment by trusktr** [comment] 2017-03-19 21:55
Oh, oops, I accidentally deleted `babel-preset-env`from `devDependencies`.

So, it _is_ working for me with npm v4.4 and a fresh install.

I just double checked (each time I deleted node_modules, and ran `npm install`, which runs babel, see my previous link), and it works every time with npm v4.4.

**Comment by adlk** [comment] 2017-03-19 21:56
Great! I'll do some tests and will get back to you asap.

**Comment by trusktr** [comment] 2017-03-19 22:00
Ah, false alarm, apparently I forgot to use `--save-dev` when I originally installed `babel-plugin-env` with npm v4, then when I nuked it and switched to npm v2, it failed, so I thought it was because of npm v2. Oops!

So, it actually was due to the package actually missing. It works great for me on npm v2 and v4.

I would be glad to check yours out. Can you can push it somewhere?

**Comment by ericnkatz** [comment] 2017-03-23 14:22
Running into similar issue for my project where I have other modules npm linked. Same issue if I just tell webpack to resolve them from their project folders directly.

**Comment by ericnkatz** [comment] 2017-03-23 14:36
@yavorsky ,
So this worked for me in the individual packages: https://github.com/babel/babel-preset-env/issues/219#issuecomment-287643182 . `npm install babel-preset-env`

**Comment by yavorsky** [comment] 2017-03-23 14:47
@ericnkatz Good! But it didn't work for you just with `babel-preset-env` in `dependencies` in `packge.json` and then `npm install`?

@adlk Did you have success with changes according to https://github.com/babel/babel-preset-env/issues/186#issuecomment-287650966?

**Comment by ericnkatz** [comment] 2017-03-23 19:24
@yavorsky in my case the package does not actually use babel at all so I don't add it to the `package.json` it is a module I've forked but want to maintain in the source of my existing project until I can PR back to its original and then get rid of the custom tailoring I've done while in development.

**Comment by ThomasBrierley** [comment] 2017-04-27 11:56
This is annoying

I'm using babel as part of a build system that can be used either globally or locally, as a result of this I have to do more messing around and construct the node_modules path for babel:

```JavaScript
const mod = (__dirname.includes(process.cwd()) ? process.cwd() : __dirname) + '/node_modules/';
// ...
.pipe(plugin.babel({presets: [[mod + 'babel-preset-env']]}))
```

Does anyone have an explanation for how this makes sense? plugins are probably always node modules, why make them relative to the input source? and for the cases when they aren't source relative paths could still be checked.

**Comment by loganfsmyth** [comment] 2017-04-27 17:00
In Babel 7.x, plugins and presets will be resolved relative to the cwd rather than relative to the file. We agree the current behavior is not something anyone wants.

**Comment by ThomasBrierley** [comment] 2017-04-28 08:52
Excellent, good news, thanks @loganfsmyth :smile:

**Comment by xtuc** [comment] 2017-04-28 11:29
@ThomasBrierley do you mind if we close this? This breaking change is also in the upgrade guide.

**Comment by ThomasBrierley** [comment] 2017-04-28 12:39
I'd say it's ok to close, however @adlk originated this issue not me.

**Comment by NorikDavtian** [comment] 2017-05-26 01:42
came to the same issue because of the documentation for the CLI option 
http://babeljs.io/docs/setup/#installation
should be
`npm install --save-dev babel-cli babel-preset-env`

is missing the `babel-preset-env`

**Comment by mo** [comment] 2017-07-23 11:19
I ran into the problem as well, everything was working fine when I were developing on project X normally. However, as soon as I did "npm link foo" inside X, then the build would fail there with the error:

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/path/to/project/foo"

The workaround that fixed it for me was to install all presets from "project X" into project "foo" (without --save or changing the package.json). In my case those were:

npm install babel-preset-es2015 babel-preset-react babel-preset-react-hmre

So I didn't even have babel-preset-env install in any of my project; the the bug is in babel itself. Hopefully it will be fixed in babel7 like @loganfsmyth said.

**Comment by mo** [comment] 2017-07-23 11:44
The cleanest workaround to this problem is probably to prefix all the presets with "babel-preset-" and then do ```.map(require.resolve)``` on the array directly in the webpack config:

```
       {
         test: /\.js$/,
         loader: 'babel-loader',
         exclude: /node_modules/,
         options: {
-          presets: ['es2015', 'react', 'react-hmre']
+          presets: [
+            'babel-preset-es2015',
+            'babel-preset-react',
+            'babel-preset-react-hmre'
+          ].map(require.resolve)
         },
```

This is explained here:
      https://stackoverflow.com/questions/34574403/how-to-set-resolve-for-babel-loader-presets/
      https://github.com/babel/babel-loader/issues/166

**Comment by 5265liu** [comment] 2017-07-28 08:10
@loganfsmyth  thankyou your answers is very helpful for me;my english is very poor ; haha

**Comment by toddbarnett** [comment] 2017-08-29 18:21
npm install --save-dev babel-preset-env 
error 404 Not Found: bable-preset-env@latest

**Comment by hzoo** [comment] 2017-08-29 19:23
make sure you clear node_modules, use a later npm version. I'm having a really hard time understanding all these issues/errors so closing (make a new issue, or better just ask in slack)

`npm install --save-dev babel-cli babel-preset-env`

**Closed by hzoo** 2017-08-29 19:23 UTC

**Comment by yhnbgfd** [comment] 2017-09-04 08:57
It works for me,modify file ".babelrc":
【Old】
{ 
  "presets": [ 
    ["env", { "modules": false }] 
  ] 
} 
【New】
{
  "presets": [
    ["latest", {
      "es2015": { "modules": false }
    }]
  ]
}

**Comment by ltfschoen** [comment] 2017-10-12 04:06
I had this error.
I resolved it by first creating a .babelrc file with the following contents in the project root folder:
```
{
  "presets": [
    [
      "env",  { "modules": false }
    ]
  ]
}
```
I then ran the following command to install this development dependency and save it to the package.json
```
npm install --save-dev babel-preset-env
```

**Comment by zanona** [comment] 2017-10-25 19:34
This is still an issue when using babelify with the option `--global-transform` rather than `--transform` it will try to search for the preset relative to the nested module being converted.
This will happen when you `link` a module that's located elsewhere locally and not flattened under `/node_modules` 

Cross-reference: https://github.com/babel/babelify/issues/134

**Comment by rwakos** [comment] 2017-10-27 19:45
Run:
`npm update`
This worked for me!
