### ISSUE TITLE
Version numbers should be string not numbers

### ISSUE THREAD

**Issue by danez** [babel/babel-preset-env#187] opened 2017-03-03 17:35 UTC
As we are currently using numbers for targets, it can happen that too much plugins get applied although not necessary.

```js
{
  node: 6.10,
}
```

This will apply unnecessary transforms as 6.1 < 6.9

```
Using targets:
{
  "node": 6.1
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"node":6.1}
  transform-es2015-for-of {"node":6.1}
  transform-es2015-function-name {"node":6.1}
  transform-exponentiation-operator {"node":6.1}
  transform-async-to-generator {"node":6.1}
  syntax-trailing-function-commas {"node":6.1}
```

**Comment by danez** [comment] 2017-03-03 18:12
#114

**Comment by spencerhakim** [comment] 2017-03-03 23:36
The [new `invertedEqualsEnv` code](https://github.com/babel/babel-preset-env/pull/180/files#diff-b7a8695388d01f5a44747b19feee2e3dR54) from #180 should be easy to modify to instead use the `semver` package, no? So that we don't have to wait for 2.0 or for #114 to be fixed and merged. I can submit a PR if that'd help.

**Comment by danez** [comment] 2017-03-08 16:19
@spencerhakim Yes true, but I'm not talking about `invertedEqualsEnv` but the user supplied options. But it will be fixed in #114.

But good catch we also need to use semver in `invertedEqualsEnv` though it cannot fail there currently as compat-table has no version '>=x.10' defined.

**Comment by yvele** [comment] 2017-03-27 08:52
I juste made https://github.com/babel/babel-preset-env/issues/227 but I'm closing it as it seems to be a duplicate of this one..

**Comment by damonmaria** [comment] 2017-04-10 09:03
I suspect this issue will become a lot more common now that AWS Lambda is running Node 6.10.

**Comment by existentialism** [comment] 2017-04-11 02:24
We landed string support in https://github.com/babel/babel-preset-env/issues/231.

I'll open another issue for supporting things like `"chrome": ">= 53"` separately!

**Closed by existentialism** 2017-04-11 02:24 UTC
Labels: bug, has pr
