### ISSUE TITLE
Ffhu

### ISSUE THREAD

**Issue by sharafulin** [babel/babel-preset-env#452] opened 2017-10-23 16:15 UTC
try{
    require('babel-polyfill');
}catch(e){
    console.warn(e);
}

**Comment by hzoo** [comment] 2017-10-23 17:38
We need a more descriptive issue to be able to help you 🙂, closing now

**Closed by hzoo** 2017-10-23 17:38 UTC

**Comment by existentialism** [comment] 2017-10-23 17:40
Assuming this is a duplicate of https://github.com/babel/babel-preset-env/issues/451 anyway
